 
 
//------------------------------------------------------------------------------
// <auto-generated>
// Layers.cs
// This code was generated by ScriptForge. To rebuild the code go to 
// Project Settings ->Script Forge and on that window hit generate all. Any
// changes made to this script will be overwritten.  
// Asset Hash: b62288ca78c2769c271afefe24922517
// </auto-generated>
//------------------------------------------------------------------------------
namespace ScriptforgeGenerated
{
	public static partial class Layers
	{
		/// <summary>
		/// An enum that contains the names of every scene that
		/// is in your project.
		/// </summary>
		public enum Types
		{
			Player,
			Enemies,
			Health,
			Live
		}

		public const string PLAYER = "Player";
		public const string ENEMIES = "Enemies";
		public const string HEALTH = "Health";
		public const string LIVE = "Live";
	}
}

