//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Diagnostics;

namespace ScriptForge
{
    public static class ExtenalLinks
    {
        public static string SCRIPT_FORGE_GOOLGE_DOC_URL = "https://docs.google.com/document/d/1bxVq8MFR5EYw3l-3sPjZjOpy0gFE45mpQFFIwYrTVQA/edit?usp=sharing";
        public static string GITHUB_REPO_URL = "https://github.com/ByronMayne/ScriptForge/";
        public static string GITHUB_ISSUES_URL = "https://github.com/ByronMayne/ScriptForge/issues";
        public static string TWITTER_URL = "https://twitter.com/byMayne";

        public static void OpenDocumentationPage()
        {
            Process.Start(SCRIPT_FORGE_GOOLGE_DOC_URL);
        }

        public static void OpenRepoPage()
        {
            Process.Start(GITHUB_REPO_URL);
        }

        public static void OpenIssuesPage()
        {
            Process.Start(GITHUB_ISSUES_URL);
        }

        public static void OpenTwitter()
        {
            Process.Start(TWITTER_URL);
        }
    }
}

