//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

namespace ScriptForge
{
	public static class FontAwesomeIcons
	{
		public static string LIFE_RING    = new string('\xf1cd', 1); 	
		public static string MAGIC        = new string('\xf0d0', 1); 
		public static string BUG          = new string('\xf188', 1); 
		public static string CUBES        = new string('\xf085', 1); 
		public static string BOOKMARK     = new string('\xf02e', 1); 
		public static string BARS         = new string('\xf0c9', 1); 
		public static string SORT_AMOUNT  = new string('\xf161', 1); 
		public static string PICTURE      = new string('\xf03e', 1); 
		public static string GAMEPAD      = new string('\xf11b', 1); 
		public static string COG          = new string('\xf013', 1); 
		public static string INFO_CIRCLE  = new string('\xf05a', 1); 
        public static string CHECKBOX     = new string('\xf058', 1);
        public static string REFRESH      = new string('\xf021', 1);
        public static string WARNING      = new string('\xf071', 1);
        public static string INFO         = new string('\x129', 1);
    }
}

