//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace ScriptForge
{
		public static class ExtenalLinks
		{
			public static string SCRIPT_FORGE_GOOLGE_DOC_URL = "https://docs.google.com/document/d/1bxVq8MFR5EYw3l-3sPjZjOpy0gFE45mpQFFIwYrTVQA/edit?usp=sharing";
		}
}

