//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace ScriptForge
{
	public static class sf_FontAwesome
	{
		public static char fa_LifeRing = '\xf1cd'; 	
		public static char fa_Magic = '\xf0d0';
		public static char fa_Bug = '\xf188';
		public static char fa_Cubes = '\xf1b3';
		public static char fa_Bookmark = '\xf02e';
		public static char fa_Bars = '\xf0c9';
		public static char fa_SortAmountDesc = '\xf161';
		public static char fa_PictureO = '\xf03e';
		public static char fa_Gamepad = '\xf11b';
		public static char fa_Cog = '\xf013';
		public static char fa_InfoCircle = '\xf05a';
	}
}

