//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.IO;
using System.Text;
using UnityEditor;
using UnityEngine;

namespace ScriptForge
{
	public class sf_ProjectSettingsLoader : MonoBehaviour
	{
		public const string SETTINGS_FOLDER_NAME = "\\ProjectSettings\\";
				
		public static string LoadText( string filename )
		{
			DirectoryInfo path = Directory.CreateDirectory( Application.dataPath );
		
			path = path.Parent;

			Debug.Log( path.FullName );

			filename = path.FullName + SETTINGS_FOLDER_NAME + filename + ".asset";

			Debug.Log( filename );

			StreamReader sr = new StreamReader(filename);
			string fileContents = sr.ReadToEnd();
			sr.Close();

			return fileContents;
		}


		private const string PROJECTSETTINGS_INPUT_NAME = "InputManager";
		[MenuItem("Help/Load Input")]
		public static void LoadInput()
		{
		  Debug.Log( LoadText( PROJECTSETTINGS_INPUT_NAME ) );
		}
	}
}

