//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace ScriptForge
{
		public static class sf_Resources
		{
			public const string EDITOR_SKIN_UNITY = "ScriptForgeSkin";
		}
}

