 
 
//------------------------------------------------------------------------------
// <auto-generated>
// Tags.cs
// This code was generated by ScriptForge. To rebuild the code go to 
// Project Settings ->Script Forge and on that window hit generate all. Any
// changes made to this script will be overwritten.  
// Asset Hash: b62288ca78c2769c271afefe24922517
// </auto-generated>
//------------------------------------------------------------------------------
namespace ScriptforgeGenerated
{
	public static partial class Tags
	{
		/// <summary>
		/// An enum that contains the names of every tag that
		/// is defined in the project.
		/// </summary>
		public enum Types
		{
			Default,
			UI,
			Editor_Only,
			Player,
			Pickups
		}

		public const string DEFAULT = "Default";
		public const string UI = "UI";
		public const string EDITOR_ONLY = "Editor_Only";
		public const string PLAYER = "Player";
		public const string PICKUPS = "Pickups";
	}
}

