//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by ScriptForge. To rebuild the code go to 
// Window->Script Forge and on that window hit generate. 
// </auto-generated>
//------------------------------------------------------------------------------
namespace ScriptForge.Generated 
{

	/// <summary>
	/// Generates a safe wrapper for Tags.
	/// </summary>
	public static class Tags
	{
		    public static readonly string Untagged = "Untagged";
		    public static readonly string Respawn = "Respawn";
		    public static readonly string Finish = "Finish";
		    public static readonly string EditorOnly = "EditorOnly";
		    public static readonly string MainCamera = "MainCamera";
		    public static readonly string Player = "Player";
		    public static readonly string GameController = "GameController";
		    public static readonly string Hero = "Hero";
		    public static readonly string Witch = "Witch";
		    public static readonly string Health_Pickup = "Health_Pickup";
		    public static readonly string Ammo_Pickup = "Ammo_Pickup";
		    public static readonly string Small_Enemy = "Small_Enemy";
		    public static readonly string Door = "Door";
		    public static readonly string Monster = "Monster";
		    public static readonly string Death_Trigger = "Death_Trigger";
		    public static readonly string Trap = "Trap";
		    public static readonly string Wall_that_no_one_can_enter = "Wall_that_no_one_can_enter";
		}
}
