
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by ScriptForge. To rebuild the code go to 
// Window->Script Forge and on that window hit generate. 
// </auto-generated>
//------------------------------------------------------------------------------
namespace Scriptforge.Generated
{
    /// <summary>
    /// Generates a wrapper for Layers.
    /// </summary>
    public static partial class Layers
    {
        /// <summary>
        /// Bitwise values are used any layer masking.
        /// </summary>
        public static class Bitwise
        {
            public static readonly int Default = 1 << Integer.Default;
            public static readonly int TransparentFX = 1 << Integer.TransparentFX;
            // Other Layers
        }

        /// <summary>
        /// Integer values are used any layer checking.
        /// </summary>
        public static class Integer
        {
            public static readonly int Default = 0;
            public static readonly int TransparentFX = 1;
            // Other Layers
        }
    }
}



