//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by ScriptForge. To rebuild the code go to 
// Project Settings ->Script Forge and on that window hit generate. 
// </auto-generated>
//------------------------------------------------------------------------------

/// <summary>
/// Generates a safe wrapper for SortingLayers.
/// </summary>
public static class SortingLayers
{
    public static readonly string Default = "Default";
    public static readonly string Forground = "Forground";
    public static readonly string Middleground = "Middleground";
    public static readonly string Background = "Background";
    public static readonly string Player = "Player";
    public static readonly string Enemies = "Enemies";
    public static readonly string Projectiles = "Projectiles";
    public static readonly string Birds = "Birds";
    public static readonly string Houses = "Houses";
    public static readonly string Cars = "Cars";
}






