 
//------------------------------------------------------------------------------
// <auto-generated>
// TestClass.cs
// This code was generated by ScriptForge. To rebuild the code go to 
// Project Settings ->Script Forge and on that window hit generate all. Any
// changes made to this script will be overwritten.  
// Asset Hash: b62288ca78c2769c271afefe24922517
// </auto-generated>
//------------------------------------------------------------------------------
namespace ScriptforgeGenerated
{
	// No namespace content defined
	public static partial class TestClass
	{
		// No class content defined
	}
}