 
 
//------------------------------------------------------------------------------
// <auto-generated>
// Scenes.cs
// This code was generated by ScriptForge. To rebuild the code go to 
// Project Settings ->Script Forge and on that window hit generate all. Any
// changes made to this script will be overwritten.  
// Asset Hash: b62288ca78c2769c271afefe24922517
// </auto-generated>
//------------------------------------------------------------------------------
namespace ScriptforgeGenerated
{
	public static partial class Scenes
	{
		public const string MAINMENU/PREFABS/BUTTON = "MainMenu/Prefabs/Button";
		public const string MAINMENU/VIEWS/LOADINGSCREEN.MP4 = "MainMenu/Views/LoadingScreen.mp4";
		public const string MAINMENU/VIEWS/OPTIONS DIALOG.PREFAB = "MainMenu/Views/Options Dialog.prefab";
	}
}

