 
 
//------------------------------------------------------------------------------
// <auto-generated>
// ResourcePaths.cs
// This code was generated by ScriptForge. To rebuild the code go to 
// Project Settings ->Script Forge and on that window hit generate all. Any
// changes made to this script will be overwritten.  
// Asset Hash: b62288ca78c2769c271afefe24922517
// </auto-generated>
//------------------------------------------------------------------------------
namespace ScriptforgeGenerated
{
	public static partial class ResourcePaths
	{
		public class MainMenu
		{
			public class Prefabs
			{
				public const string BUTTON = "Button.prefab";
			}

			public class Views
			{
				public const string LOADINGSCREEN = "LoadingScreen.mp4";
				public const string OPTIONS_DIALOG = "Options %@#$@#%Dialog.prefab";
			}

		}

		public class Audio
		{
			public class Sound_Effects
			{
				public const string BOOM = "Boom.mp3";
			}

		}

	}
}

